### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by ZhongJunhong** [realzza/birdData#11]
您好，我在尝试批量下载的时候，发现当查询结果为0个的时候，会出现 `ZeroDivisionError: integer division or modulo by zero` 的错误，查询`trackback`，错误源头在`utils.py`文件的**第4行**：`portion = len(lst) //n`的位置。

除此之外，我还发现当查询以下物种名称的时候也会出现同样的error。我的查询时间范围是从1971-01-01：

```
['Maleo', 'Moluccan Megapode', 'Nicobar Megapode', 'Long-billed Partridge', 'Black Partridge', 'Udzungwa Forest Partridge', 'Rubeho Forest Partridge', "Roll's Partridge", 'Sumatran Partridge', 'Grey-breasted Partridge', 'Red-billed Partridge', 'Chestnut-necklaced Partridge', 'Crestless Fireback', 'Crested Fireback', 'Siamese Fireback', 'Great Argus', 'Madagascan Pochard']
```

以下这个list是对应以上的common_name的查询结果数量

```
[7, 6, 2, 18, 3, 6, 34, 10, 1, 31, 8, 35, 1, 17, 24, 83, 5]
```

期待回复，感谢！

**Comment by realzza** [comment]
Thanks for reporting this issue. This issue may be of reference to other users as well, so I'll reply in English : )

The xeno-canto API mainly causes this issue. Due to protection towards certain birds, they will limit public usage and access to the recordings of certain species from the interface. If you go to the xeno-canto [site](https://xeno-canto.org/species/Eulipoa-wallacei) of birds you mentioned above, you will see a warning "Recordings of this species are currently restricted. [Explain this.](https://xeno-canto.org/help/FAQ#restricted)"

Despite the limitations of the API, thanks for bringing forward this issue. I have added a notice for this when downloading recordings of restricted species. You should be able to see them by upgrading this package.
```
pip install xenopy==0.0.5a1
``` 

Let me know if you have further questions. Have fun!
